### ISSUE TITLE
state: title screen

### ISSUE THREAD

**Issue by mwcz** [CommandLineHeroes/clh-bash#13]
Here's the general layout of the title screen:

![screenshot from 2019-01-18 17-19-05](https://user-images.githubusercontent.com/364615/51415842-3c4ec780-1b45-11e9-9828-9a1127e9e1c6.png)

To complete this issue...

create a function to "enter" the title screen which does the following:

- [x] positions the camera
- [x] blanks out the computer screen
- [x] adds 'type "play"' to the screen
- [x] when player types "play", transition to the play state
- [x] displays the CLH logo
- [x] displays credits "created by Jared Sprague, Michael Clayton, and Eric Kramer"
- [x] displays link to repo, maybe?

The above can be roughly laid out, they don't have to be perfect, we can fine tune and tweak later.

**Comment by Jared-Sprague** [comment]
![screenshot from 2019-01-30 11-09-52](https://user-images.githubusercontent.com/3926730/51994879-a76e9700-247f-11e9-9671-9db2555972ac.png)

**Comment by Jared-Sprague** [comment]
![screenshot from 2019-02-06 09-54-54](https://user-images.githubusercontent.com/3926730/52349830-53226480-29f5-11e9-82a9-783a04808e55.png)

**Comment by mwcz** [comment]
Calling this done.
