### ISSUE TITLE
JSON (js keyword) isn't recognized

### ISSUE THREAD

**Issue by LiquidityC** [CommandLineHeroes/clh-bash#43]
The keyword "JSON" is sometimes proposed as a golden keyword for js but when entered it is never recognized as a valid command.

**Comment by LiquidityC** [comment]
Ok, so further digging. Typing "JSON" isn't recognized whilst typing "json" is. But when listed as a golden command the word is in capital letters. Eg. "JSON". This is sorta confusing.

**Comment by mwcz** [comment]
I have #35 on my plate to fix this, thanks for the report!  Closing this but #35 will get done for sure.

**Comment by LiquidityC** [comment]
Great. Thanks
