### ISSUE TITLE
drastically increase the recording levels of sound FX

### ISSUE THREAD

**Issue by Jared-Sprague** [CommandLineHeroes/clh-bash#67]
to be heard over the music

**Comment by mwcz** [comment]
I don't understand how the change fixes this.  I had the music volume low and you turned it up to max.  If anything the music volume needs to be even lower for the sfx to be heard.

**Comment by Jared-Sprague** [comment]
If you cant hear the sound fx because of the music,   You ether need to turn the music down,   Or make the sound fx louder.   Turning the music dound made it very hard to hear anything at the show.  So I think the second option is better make the sound fx louder,   Not through howler,  but during creattion.   Compare with pity about earth the sound fx are suuuper loud,  and the music is too during the show when people are playing pity about earth the sound fx when the rocks hit the paddle it shakes the arcade cabinet it so loud and sounds great  and the music is loud too.   The problem with bash is that the music is loud but the sound fx are super quiet.  We need to make bash sound fx more like PAE

**Comment by mwcz** [comment]
I understand the problem, I was questioning the patch because it makes the stated problem worse.  Though it does make sense that the volume needs to be similar to other games in the cab.

It should only take a minute or two to amplify the sfx with Audacity.
