### ISSUE TITLE
Error upon running "npm run extract"

### ISSUE THREAD

**Issue by ronknight** [CommandLineHeroes/clh-bash#80]
I just cloned the repo on a Windows 10 pc, I also run the "npm install" command, but I got this error after running "npm run extract". Please help. 

![image](https://user-images.githubusercontent.com/7566286/57485483-ab6d3a80-7260-11e9-9657-e23bde2a0411.png)

I was able to execute the "npm start" command, but it got stuck at the splash page where it shows, downloading.

**Comment by Jared-Sprague** [comment]
@ronknight  Hello!  The npm extract script won't work on windows.   But it's not required.  All it does is a convinience to extract all the gzipped 3D model files.  You can see the path of the files in the error message:  assets/models/*.gz

A work around it to just manually extract the *.gz files in that directory,  using any windows unzipping utility that supports gzip.  

If you can think of a way to do this in windows using an npm script we would love a PR!

**Comment by Jared-Sprague** [comment]
Also I update the README with that info for the extract step:

https://github.com/CommandLineHeroes/clh-bash/blob/master/README.md

**Comment by ronknight** [comment]
Hi @Jared-Sprague, I just requested a PR. That should fix the issue. Please let me know if you see any issues. Thanks.
