### ISSUE TITLE
Really slow interface

### ISSUE THREAD

**Issue by sneha-saj** [CommandLineHeroes/clh-bash#84]
> When the game starts for a few minutes nothing happens on the screen.
> No proper instructions.
> Interface is really slow even when it comes to typing the commands.

**Comment by mwcz** [comment]
Hi @Sneha0104, would you mind sharing some information about your OS and graphics card?

**Comment by sneha-saj** [comment]
Thank you for your email.

  Operating System: Pop!_OS 20.04 LTS
  Graphics Card:  Intel Corporation HD Graphics 620

**Comment by mwcz** [comment]
Thanks @Sneha0104.  That graphics card should be enough to run the game, in fact it's the same card that my laptop has.  I should have also asked what web browser you're using.  The game requires 3D acceleration and some web browsers don't support hardware accel on certain OS/GPU/driver combinations.  If you're using a Chromium-based browser, you can open a tab to `about:gpu` and if you see "WebGL: Hardware accelerated" then your browser is using the GPU for WebGL.

**Comment by sneha-saj** [comment]
Thank you for your reply.
