### ISSUE TITLE
command list: bash

### ISSUE THREAD

**Issue by mwcz** [CommandLineHeroes/clh-bash#9]
Get all bash:

- keywords
- built-ins
- anything else?

**Comment by Jared-Sprague** [comment]
Here is a list from fresh install of fedora:
[from-path-fedora.txt](https://github.com/CommandLineHeroes/clh-bash/files/2829579/from-path-fedora.txt)

**Comment by Jared-Sprague** [comment]
Here is a list from fresh install of ubuntu:
[from-path-ubuntu.txt](https://github.com/CommandLineHeroes/clh-bash/files/2829973/from-path-ubuntu.txt)
