### ISSUE TITLE
Background image is overlapping

### ISSUE THREAD

**Issue by JinKRJPEN** [CommandLineHeroes/clh-bash#91]
Background image is overlapping. Is it intended? (e.g. downloading)

**Comment by mwcz** [comment]
@Yesthink Thanks for the bug report. Would you mind sharing a screenshot, and what browser+version you're using?

**Comment by JinKRJPEN** [comment]
Thanks for responding.
But it disappeared after refreshing, and the same thing doesn't happen anymore.
I used google chrome browser ver. 91.0.4472.106.

**Comment by mwcz** [comment]
Odd, hopefully it was a weird fluke.  Please reopen if it happens again.
